"""The seams between the lanes, exercised as one system.

Five agents wrote ``jarvis_bots``: the framework, the generator, the poke
plugin, the gate and this.  Each lane's own suite checks it against
``contracts.py``; none of them can check the thing the package actually
claims, which ``contracts.py`` states in its first paragraph -- "the point
of this module is that it [the Pokemon assistant] is not special.  Adding
the second bot should be a class and a page, not a refactor."

So what is tested here is only what needs more than one lane:

* **the package's front door** -- :mod:`jarvis_bots` re-exports a usable
  surface and no name it binds shadows a submodule, which would make
  ``from jarvis_bots import registry`` mean different things depending on
  what had been imported first;
* **the attention lifecycle across the lanes** -- the scaffold template and
  :class:`~jarvis_bots.bots.poke_bot.PokeBot` both close a request for a
  decision by re-raising the key below ACTION with
  :data:`~jarvis_bots.supervisor.RESOLVED_FLAG` set, and the supervisor
  reads it.  Before the fix this claim was an ``xfail`` in the scaffold
  suite: the badge could be filled and never emptied;
* **the platform claim, run** -- a bot generated by ``new-bot``, with no
  edit, registered beside ``PokeBot`` under one supervisor for twenty
  rounds;
* **the page contract** -- ``launcher_state`` against ``web/README.md``
  *and* against the demo dataset ``web/bots.html`` renders, so the page
  cannot drift from the supervisor in silence;
* **the delivery seam** -- a bot's ACTION event through the real
  :class:`jarvis_alerts.api.AlertService`, outbox and worker to a
  transport, which is the one path where the two packages' signatures have
  to agree exactly;
* **determinism** -- the same seed and the same clock give the same
  transcript in a separate process, under a different ``PYTHONHASHSEED``.

Nothing here sleeps, opens a socket or reads a real clock.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

import pytest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import jarvis_bots
from jarvis_bots import (
    BaseBot,
    BotInfo,
    BotRegistry,
    BotState,
    BotStatus,
    Severity,
    Supervisor,
)
from jarvis_bots.scaffold import new_bot
from jarvis_bots.supervisor import RESOLVED_FLAG

WEB = ROOT / "jarvis_bots" / "web"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


class Clock:
    """The injected clock: it moves when a test moves it, and never else."""

    def __init__(self, at: float = 1_700_000_000.0) -> None:
        self.at = float(at)

    def __call__(self) -> float:
        return self.at

    def advance(self, by: float) -> None:
        self.at += float(by)


class ScriptedBot(BaseBot):
    """A bot whose whole behaviour is a list of (severity, key, resolved).

    Small enough to read, which matters: the point of these tests is what
    the *supervisor* does with what a bot returns, so the bot must not be
    interesting.
    """

    def __init__(self, clock, bot_id: str = "scripted", script=()) -> None:
        super().__init__(
            clock,
            BotInfo(id=bot_id, name=bot_id.title(), blurb="scripted",
                    kind="radar", interval_s=300.0, href=f"/bots/{bot_id}"),
        )
        self._script = list(script)
        self._n = 0

    def tick(self, now):
        step = self._script[self._n] if self._n < len(self._script) else ()
        self._n += 1
        events = []
        for severity, key, resolved in step:
            data = {RESOLVED_FLAG: resolved} if resolved is not None else {}
            events.append(
                self.event(severity, f"{self.id} step {self._n}",
                           attention_key=key, href=self.info.href, **data)
            )
        return events

    def status(self):
        return BotStatus(
            BotState.RUNNING if self._n else BotState.IDLE,
            stats=(self.stat("Ticks", str(self._n)),),
        )


def run_rounds(supervisor: Supervisor, clock: Clock, n: int, step: float = 600.0):
    reports = []
    for _ in range(n):
        reports.append(supervisor.run_round(clock.at))
        clock.advance(step)
    return reports


def demo_state_from_page() -> Dict[str, Any]:
    """``DEMO_STATE`` out of ``bots.html``, as data.

    It is a JavaScript object literal with bare keys, so the keys are
    quoted and then parsed as JSON.  Nothing is executed: the page is read,
    never run.
    """
    text = (WEB / "bots.html").read_text(encoding="utf-8")
    match = re.search(r"const DEMO_STATE = (\{.*?\n\});", text, re.S)
    assert match is not None, "bots.html no longer carries a DEMO_STATE"
    body = re.sub(r"//[^\n]*", "", match.group(1))
    body = re.sub(r"(^|[{,\s])([A-Za-z_][A-Za-z0-9_]*)\s*:", r'\1"\2":', body)
    return json.loads(re.sub(r",(\s*[}\]])", r"\1", body))


def readme_payloads() -> List[Dict[str, Any]]:
    """The JSON blocks ``web/README.md`` documents, in order: badge, page,
    then the per-bot detail payload."""
    text = (WEB / "README.md").read_text(encoding="utf-8")
    return [json.loads(b) for b in re.findall(r"```json\n(.*?)```", text, re.S)]


def json_shape(value: Any) -> Any:
    """An object reduced to its keys and the JSON type of each leaf."""
    if isinstance(value, dict):
        return {k: json_shape(v) for k, v in sorted(value.items())}
    if isinstance(value, list):
        return [json_shape(value[0])] if value else []
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if value is None:
        return "null"
    return "str"


# ---------------------------------------------------------------------------
# the package's front door
# ---------------------------------------------------------------------------


def test_the_package_exports_a_usable_surface():
    """One import is enough to write, wire and run a bot."""
    for name in (
        "BaseBot", "BotInfo", "BotRegistry", "BotState", "BotStatus", "Bot",
        "Event", "Severity", "Stat", "Supervisor", "SupervisorError",
        "JsonFileStore", "Health", "RoundReport", "AttentionItem",
        "RegistryError", "new_bot", "ScaffoldError", "parse_severity",
        "check_bot", "backoff_interval",
    ):
        assert name in jarvis_bots.__all__, f"{name} is not exported"
        assert getattr(jarvis_bots, name) is not None


def test_nothing_exported_shadows_a_submodule():
    """``from jarvis_bots import registry`` must always mean the module.

    If the package bound a class or a function under a submodule's name the
    attribute would be one thing before that submodule was imported and
    another after, so the bug would depend on import order.
    """
    assert not jarvis_bots.SUBMODULES.intersection(jarvis_bots.__all__)
    for name in sorted(jarvis_bots.SUBMODULES):
        path = ROOT / "jarvis_bots" / name
        if not path.exists() and not path.with_suffix(".py").exists():
            continue  # a name reserved ahead of the module existing
        assert name not in jarvis_bots.__all__
        assert not hasattr(jarvis_bots, name) or getattr(
            jarvis_bots, name
        ).__class__.__name__ == "module"


def test_every_submodule_still_imports_under_its_own_name():
    import jarvis_bots.base
    import jarvis_bots.bots
    import jarvis_bots.cli
    import jarvis_bots.contracts
    import jarvis_bots.registry
    import jarvis_bots.scaffold
    import jarvis_bots.supervisor
    import jarvis_bots.validate

    for module in (
        jarvis_bots.base, jarvis_bots.bots, jarvis_bots.cli,
        jarvis_bots.contracts, jarvis_bots.registry, jarvis_bots.scaffold,
        jarvis_bots.supervisor, jarvis_bots.validate,
    ):
        assert module.__name__.startswith("jarvis_bots.")


def test_importing_the_package_reads_no_clock_and_draws_no_randomness():
    """contracts.py: "Time is injected everywhere."

    ``jarvis_bots.cli`` is the composition root and may import ``time``;
    importing the *package* must not, or a bot could reach a wall clock
    without anyone wiring one.
    """
    import ast

    tree = ast.parse((ROOT / "jarvis_bots" / "__init__.py").read_text(encoding="utf-8"))
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)
    for forbidden in ("time", "random", "socket", "urllib", "urllib.request",
                      "jarvis_bots.cli", "jarvis_bots.validate"):
        assert forbidden not in imported, f"__init__.py imports {forbidden}"
    assert "jarvis_bots.contracts" in imported


# ---------------------------------------------------------------------------
# the attention lifecycle, across the lanes
# ---------------------------------------------------------------------------


def test_a_resolution_event_closes_the_badge_item():
    """The convention every bot in this package writes against.

    contracts.py has the badge count "distinct open keys" and gives a bot
    no way to close one.  The supervisor reads the flag both shipped bots
    already set, so a question that has been answered leaves the badge.
    """
    clock = Clock()
    bot = ScriptedBot(clock, "scripted", [
        [(Severity.ACTION, "k", None)],                # opens
        [(Severity.ACTION, "k", None)],                # the same question
        [(Severity.NOTICE, "k", True)],                # answered
        [],
    ])
    sup = Supervisor(BotRegistry([bot]), clock)
    counts = []
    for _ in range(4):
        sup.run_round(clock.at)
        counts.append(sup.attention_count())
        clock.advance(600.0)
    assert counts == [1, 1, 0, 0]


def test_a_resolution_needs_the_flag_and_a_sub_action_severity():
    """Three near misses that must *not* empty the badge.

    A key mentioned in a feed line, a truthy-but-not-True flag, and a
    resolution raised at ACTION (which contracts.py reads as a request for
    a decision, so it re-opens rather than closes).
    """
    clock = Clock()
    bot = ScriptedBot(clock, "near-miss", [
        [(Severity.ACTION, "k", None)],
        [(Severity.NOTICE, "k", None)],     # a line in the feed, no flag
        [(Severity.NOTICE, "k", "yes")],    # truthy, not True
        [(Severity.ACTION, "k", True)],     # asks and answers: asking wins
        [(Severity.NOTICE, "k", True)],     # the real thing
    ])
    sup = Supervisor(BotRegistry([bot]), clock)
    counts = []
    for _ in range(5):
        sup.run_round(clock.at)
        counts.append(sup.attention_count())
        clock.advance(600.0)
    assert counts == [1, 1, 1, 1, 0]


def test_a_closed_question_asked_again_earns_a_fresh_push():
    """Closing drops the alert memory with the item.

    Otherwise the second restock of the same product at the same price --
    genuinely new news -- would be silently swallowed as a repeat.
    """
    published: List[Any] = []
    clock = Clock()
    bot = ScriptedBot(clock, "again", [
        [(Severity.ACTION, "k", None)],
        [(Severity.ACTION, "k", None)],
        [(Severity.NOTICE, "k", True)],
        [(Severity.ACTION, "k", None)],
    ])
    sup = Supervisor(BotRegistry([bot]), clock, alerts=published.append)
    reports = run_rounds(sup, clock, 4)
    assert [r.alerts for r in reports] == [1, 0, 0, 1]
    assert len(published) == 2


def test_a_resolution_for_a_key_that_is_not_open_is_harmless():
    """A restarted bot may answer a question the supervisor forgot."""
    clock = Clock()
    bot = ScriptedBot(clock, "orphan", [[(Severity.NOTICE, "k", True)]])
    sup = Supervisor(BotRegistry([bot]), clock)
    report = sup.run_round(clock.at)
    assert report.events == 1 and sup.attention_count() == 0


def test_a_generated_bot_closes_its_own_attention(tmp_path):
    """The template's convention and the supervisor's reader, end to end.

    This is the cross-lane claim: the generator emits a bot that resolves
    its own request, and the framework -- written by a different agent
    against the same contract -- acts on it, with no app-side glue.
    """
    module = _import_generated(tmp_path, "inbox-watch")
    watched = tmp_path / "watched"
    watched.mkdir()
    for name in ("a", "b"):
        (watched / name).write_text("x", encoding="utf-8")

    clock = Clock()
    bot = module.build(clock=clock, watch_dir=str(watched), threshold=2)
    sup = Supervisor(BotRegistry([bot]), clock)
    sup.run_round(clock.at)
    assert sup.badge_status()["attention"] == 1

    (watched / "a").unlink()
    (watched / "b").unlink()
    clock.advance(3600.0)
    sup.run_round(clock.at)
    assert sup.badge_status()["attention"] == 0
    assert sup.badge_status()["state"] == "ok"


def test_the_poke_bot_closes_its_own_attention_with_no_app_side_glue():
    """``close_resolved`` was the workaround; the framework now does it.

    The helper stays -- it is harmless and an app may still drive it -- but
    a supervisor running PokeBot with nothing wired after the round must
    reach an empty badge when the deal goes away.
    """
    poke_bot = pytest.importorskip("jarvis_bots.bots.poke_bot")
    fleet = _build_poke(poke_bot)
    clock, bot = fleet["clock"], fleet["bot"]
    sup = Supervisor(BotRegistry([bot]), clock)

    seen_open = False
    for _ in range(40):
        sup.run_round(clock.at)
        seen_open = seen_open or sup.attention_count() > 0
        fleet["step"]["n"] += 1
        clock.advance(1800.0)
    assert seen_open, "the scripted shop never produced a BUY"
    assert sup.attention_count() == 0, sup.attention_items()
    assert bot.open_attention_keys() == []


# ---------------------------------------------------------------------------
# the platform claim
# ---------------------------------------------------------------------------


def _import_generated(tmp_path: Path, bot_id: str):
    """Generate a bot into ``tmp_path`` and import it, unedited."""
    import importlib.util

    dest = tmp_path / "gen"
    paths = new_bot(bot_id=bot_id, name="Stock watcher",
                    blurb="Watches a folder.", kind="radar", dest_dir=dest)
    spec = importlib.util.spec_from_file_location(paths[0].stem, paths[0])
    module = importlib.util.module_from_spec(spec)
    sys.modules[paths[0].stem] = module
    try:
        spec.loader.exec_module(module)
    finally:
        sys.modules.pop(paths[0].stem, None)
    return module


def _build_poke(poke_bot):
    """PokeBot over a scripted shop: cheap, then dearer, then sold out."""
    from jarvis_poke.catalog import Catalog
    from jarvis_poke.contracts import Budget, FetchResult, Observation, Rule, Stock
    from jarvis_poke.engine import DecisionEngine
    from jarvis_poke.prices import PriceHistory
    from jarvis_poke.rules import RuleSet
    from jarvis_poke.sources import MemoryPollStore, PollScheduler, load_policies

    clock = Clock()
    step = {"n": 0}
    catalog = Catalog.load()
    watched = [p.id for p in catalog.products()[:3]]
    rules = RuleSet(
        [Rule(product_id=pid, max_price=5500, cooldown_s=1800.0) for pid in watched],
        budget=Budget(total=50_000),
    )
    history = PriceHistory()
    engine = DecisionEngine(catalog, rules, history, clock)
    scheduler = PollScheduler(catalog, load_policies(), clock, MemoryPollStore())

    def fetcher(url, headers, policy):
        return FetchResult(ok=True, status=200, body="<fake/>")

    def parser(sku, body, at):
        n = step["n"]
        out = Stock.OUT_OF_STOCK if n >= 9 else Stock.IN_STOCK
        return Observation(
            product_id=sku.product_id, source=sku.source, sku=sku.sku, at=at,
            stock=out, price=None if out is Stock.OUT_OF_STOCK else 4200,
            shipping=0, url=sku.url,
        )

    bot = poke_bot.PokeBot(catalog, rules, history, engine, scheduler,
                           fetcher, parser, clock)
    return {"clock": clock, "bot": bot, "step": step}


def test_a_generated_bot_runs_beside_the_poke_bot(tmp_path):
    """contracts.py's opening claim, as a running system.

    Two bots written months and lanes apart, one registry, one supervisor,
    twenty rounds: both appear on the launcher with the state the
    supervisor owns, and pausing one leaves the other running.
    """
    poke_bot = pytest.importorskip("jarvis_bots.bots.poke_bot")
    module = _import_generated(tmp_path, "restock")
    watched = tmp_path / "watched"
    watched.mkdir()
    for i in range(5):
        (watched / f"f{i}").write_text("x", encoding="utf-8")

    fleet = _build_poke(poke_bot)
    clock = fleet["clock"]
    generated = module.build(clock=clock, watch_dir=str(watched), threshold=2)

    registry = BotRegistry()
    registry.register_from({"poke": fleet["bot"], "restock": generated})
    sup = Supervisor(registry, clock)
    assert registry.ids() == ["poke", "restock"]

    for r in range(20):
        sup.run_round(clock.at)
        if r == 9:
            sup.pause("restock")
        fleet["step"]["n"] += 1
        clock.advance(1800.0)

    state = sup.launcher_state(clock.at)
    cards = {c["id"]: c for c in state["bots"]}
    assert list(cards) == ["poke", "restock"], "registration order is tick order"
    assert cards["poke"]["state"] == BotState.RUNNING.ui
    assert cards["poke"]["kind"] == "cart"
    assert cards["restock"]["state"] == BotState.PAUSED.ui
    assert cards["restock"]["kind"] == "radar"
    assert cards["restock"]["attention"] == 0, "paused means no attention"
    assert sup.badge_status()["state"] == "warn"

    sup.resume("restock")
    after = {c["id"]: c["state"] for c in sup.launcher_state(clock.at)["bots"]}
    assert after == {"poke": BotState.RUNNING.ui, "restock": BotState.RUNNING.ui}
    assert sup.badge_status()["state"] == "ok"

    # Neither bot's health was touched by the other.
    assert sup.health("poke").consecutive_failures == 0
    assert sup.health("restock").consecutive_failures == 0
    assert sup.quarantined_ids() == []


def test_a_generated_bot_needs_no_edit_to_run(tmp_path):
    """Whatever ``new-bot`` writes is what runs: byte for byte."""
    dest = tmp_path / "gen"
    paths = new_bot(bot_id="restock", name="Stock watcher", blurb="Watches.",
                    kind="radar", dest_dir=dest)
    before = paths[0].read_bytes()
    module = _import_generated(tmp_path / "again", "restock")
    clock = Clock()
    bot = module.build(clock=clock, watch_dir=str(tmp_path), threshold=99)
    Supervisor(BotRegistry([bot]), clock).run_round(clock.at)
    assert paths[0].read_bytes() == before


# ---------------------------------------------------------------------------
# the page contract
# ---------------------------------------------------------------------------


def test_launcher_state_matches_the_readme_key_for_key():
    """``web/README.md`` is the contract the page is written against.

    A key the page does not know is ignored in silence; a key it wants and
    does not get renders as blank.  So the check is on the key *set* and
    the key *order*, both ways.
    """
    badge_doc, page_doc, detail_doc = readme_payloads()
    clock = Clock()
    bot = ScriptedBot(clock, "poke", [[(Severity.ACTION, "k", None)]])
    sup = Supervisor(BotRegistry([bot]), clock)
    sup.run_round(clock.at)

    badge = sup.badge_status()
    assert list(badge) == list(badge_doc)
    assert json_shape(badge) == json_shape(badge_doc)
    assert badge["state"] in {"ok", "warn", "error"}

    page = sup.launcher_state(clock.at)
    assert sorted(page) == sorted(page_doc)
    assert list(page["bots"][0]) == list(page_doc["bots"][0]), "card key order"
    assert json_shape(page["bots"][0]) == json_shape(page_doc["bots"][0])
    assert json.loads(json.dumps(page)) == page

    # The fourth endpoint, which web/README.md documents and
    # jarvis_bots/api.py serves: the card, plus detail, plus the bot's open
    # questions and its recent events.  The generated detail page reads
    # exactly this and nothing in the package could produce it before.
    detail = sup.bot_detail("poke", clock.at)
    assert sorted(detail) == sorted(detail_doc)
    documented = set(detail_doc["bot"]) - {"…"}
    assert documented <= set(detail["bot"]), sorted(documented - set(detail["bot"]))
    for key in ("attention_items", "events"):
        assert json_shape(detail["bot"][key]) == json_shape(detail_doc["bot"][key])
    assert json.loads(json.dumps(detail)) == detail


def test_launcher_state_matches_the_dataset_the_page_actually_renders():
    """``bots.html`` falls back to ``DEMO_STATE`` with no API configured.

    That object, not the README, is what ``render()`` reads, so it is the
    one that can drift.  Every path in it must exist in the supervisor's
    payload with the same JSON type, and the supervisor must emit no path
    the page will not read.
    """
    demo = demo_state_from_page()
    clock = Clock()
    bot = ScriptedBot(clock, "poke", [[(Severity.ACTION, "k", None)]])
    sup = Supervisor(BotRegistry([bot]), clock)
    sup.run_round(clock.at)
    live = sup.launcher_state(clock.at)

    assert sorted(demo) == sorted(live)
    assert json_shape(demo["bots"][0]) == json_shape(live["bots"][0])
    assert json_shape(demo["bots"][0]["stats"]) == json_shape(live["bots"][0]["stats"])


def test_every_state_word_the_page_knows_is_a_state_the_supervisor_emits():
    """``STATE_WORD`` in ``bots.html`` spells out each state.

    "State is never carried by colour alone" (web/README.md), so a state
    the page has no word for renders as nothing at all.
    """
    text = (WEB / "bots.html").read_text(encoding="utf-8")
    match = re.search(r"const STATE_WORD = \{(.*?)\};", text, re.S)
    assert match is not None
    page_states = set(re.findall(r"(\w+)\s*:", match.group(1)))
    assert page_states == {s.ui for s in BotState}


def test_the_page_and_the_supervisor_agree_on_the_icon_kinds():
    """``kind`` picks the icon; an unknown kind must fall back, not vanish."""
    from jarvis_bots.scaffold import KNOWN_KINDS

    text = (WEB / "bots.html").read_text(encoding="utf-8")
    match = re.search(r"const ICONS = \{(.*?)\n\};", text, re.S)
    assert match is not None
    icons = set(re.findall(r"^\s*(\w+)\s*:", match.group(1), re.M))
    assert set(KNOWN_KINDS) <= icons, sorted(set(KNOWN_KINDS) - icons)
    assert "bot" in icons, "there must be a generic glyph"


# ---------------------------------------------------------------------------
# the delivery seam
# ---------------------------------------------------------------------------


def test_an_action_event_reaches_a_transport_through_the_real_alert_service():
    """The one seam where two packages' signatures must agree exactly.

    ``Supervisor._publish`` calls ``publish(profile, kind, title, body,
    data=, priority=, dedupe_key=)``.  A fake with a loose signature would
    accept anything; the real service would not, and the failure would be
    swallowed into ``last_alert_error`` and never seen.
    """
    alerts = pytest.importorskip("jarvis_alerts")
    from jarvis_alerts.outbox import no_jitter

    clock = Clock()
    store = alerts.MemoryStore(clock)
    service = alerts.AlertService(store, clock,
                                  id_source=lambda: f"id-{int(clock.at)}")
    store.register(alerts.Subscription(
        profile_id="owner", device_id="phone", transport="fake",
        blob="fake://phone", created_at=clock.at,
    ))
    transport = alerts.FakeTransport()
    worker = alerts.Worker(store, {"fake": transport}, clock, no_jitter)

    bot = ScriptedBot(clock, "poke", [
        [(Severity.ACTION, "k", None)],
        [(Severity.ACTION, "k", None)],     # the same question: no second push
        [(Severity.NOTICE, "k", True)],     # a resolution is below the threshold
    ])
    sup = Supervisor(BotRegistry([bot]), clock, alerts=service)

    delivered = 0
    for _ in range(3):
        sup.run_round(clock.at)
        delivered += worker.run_once().delivered
        clock.advance(600.0)

    assert sup.last_alert_error == "", sup.last_alert_error
    assert delivered == 1, "one open question is one push"
    assert transport.calls_for("owner", "phone") == 1


def test_an_alert_service_that_is_down_does_not_fail_the_round():
    """contracts.py: a bot that had something to say is not punished for
    the notifier being broken, and the failure is visible rather than
    silent."""
    class Broken:
        def publish(self, *args, **kwargs):
            raise RuntimeError("notifier down")

    clock = Clock()
    bot = ScriptedBot(clock, "noisy", [[(Severity.ACTION, "k", None)]])
    sup = Supervisor(BotRegistry([bot]), clock, alerts=Broken())
    report = sup.run_round(clock.at)
    assert report.failed == 0 and report.events == 1 and report.alerts == 0
    assert "notifier down" in sup.last_alert_error
    assert sup.attention_count() == 1, "the badge is not the notifier's job"
    assert sup.health("noisy").consecutive_failures == 0


# ---------------------------------------------------------------------------
# persistence and determinism
# ---------------------------------------------------------------------------


def test_a_closed_question_stays_closed_across_a_restart(tmp_path):
    """The resolution must survive the save, or the badge refills on boot."""
    from jarvis_bots import JsonFileStore

    path = str(tmp_path / "state.json")
    clock = Clock()
    bot = ScriptedBot(clock, "restarter", [
        [(Severity.ACTION, "k", None)],
        [(Severity.NOTICE, "k", True)],
    ])
    sup = Supervisor(BotRegistry([bot]), clock, store=JsonFileStore(path))
    run_rounds(sup, clock, 2)
    sup.save_state()
    assert sup.attention_count() == 0

    clock2 = Clock(clock.at)
    bot2 = ScriptedBot(clock2, "restarter", [])
    sup2 = Supervisor(BotRegistry([bot2]), clock2, store=JsonFileStore(path))
    assert sup2.load_state() is True
    assert sup2.attention_count() == 0
    assert sup2.badge_status() == {"attention": 0, "state": "ok"}


def test_the_framework_gate_is_identical_in_another_process_and_hash_seed():
    """A gate whose result depends on ``PYTHONHASHSEED`` is not a gate.

    The only randomness the package may draw is a ``lucifer_gen.seed``
    stream, and nothing may iterate a set or a hash-ordered dict where the
    order reaches the report.
    """
    script = (
        "import json;"
        "from jarvis_bots.validate import run_gate;"
        "print(json.dumps(run_gate(140, 1).to_dict(), sort_keys=True))"
    )
    outputs = []
    for hash_seed in ("0", "1", "424242"):
        env = dict(os.environ, PYTHONHASHSEED=hash_seed)
        proc = subprocess.run([sys.executable, "-c", script], cwd=str(ROOT),
                              env=env, capture_output=True, text=True)
        assert proc.returncode == 0, proc.stderr
        outputs.append(proc.stdout)
    assert outputs[0] == outputs[1] == outputs[2]
    assert json.loads(outputs[0])["ok"] is True


def test_the_cli_drives_a_two_bot_fleet_across_processes(tmp_path):
    """``pause`` that forgets itself on exit is not a pause.

    Three separate interpreters: run a round, pause a bot, read the badge.
    The third has to see the second's decision, which only works if the
    state file carries it.
    """
    pytest.importorskip("jarvis_bots.bots.poke_bot")
    wiring = tmp_path / "wiring.py"
    dest = tmp_path / "gen"
    new_bot(bot_id="restock", name="Stock watcher", blurb="Watches.",
            kind="radar", dest_dir=dest)
    wiring.write_text(
        "import sys\n"
        f"sys.path.insert(0, {str(dest)!r})\n"
        "import restock\n"
        "def BOTS(clock):\n"
        "    bot = restock.build(clock=clock, watch_dir=%r, threshold=99)\n"
        "    return {bot.info.id: bot}\n" % str(dest),
        encoding="utf-8",
    )
    state = tmp_path / "state.json"
    env = dict(os.environ, PYTHONPATH=f"{ROOT}{os.pathsep}{tmp_path}")

    def cli(*argv):
        proc = subprocess.run(
            [sys.executable, "-m", "jarvis_bots.cli", *argv,
             "--bots", "wiring", "--state", str(state)],
            cwd=str(ROOT), env=env, capture_output=True, text=True,
        )
        assert proc.returncode == 0, proc.stderr
        return proc.stdout

    assert "ticked=1" in cli("round")
    assert "paused restock" in cli("pause", "--id", "restock")
    assert json.loads(cli("status")) == {"attention": 0, "state": "warn"}
    card = json.loads(cli("state"))["bots"][0]
    assert card["id"] == "restock" and card["state"] == "paused"
    assert "resumed restock" in cli("resume", "--id", "restock")
    assert json.loads(cli("status"))["state"] == "ok"


def test_the_boundary_holds_across_every_module_in_the_package():
    """SCOPE: nothing here performs a purchase, a payment or a transaction.

    Checked against the source of every shipped module rather than against
    a promise in a docstring, because the promise is what an added lane
    would keep while adding the call.
    """
    import io
    import tokenize

    banned = re.compile(
        r"^(checkout|add_to_cart|place_order|charge_card|capture_payment|"
        r"submit_payment|purchase|pay|buy_now)$", re.I
    )
    scanned = 0
    for path in sorted((ROOT / "jarvis_bots").rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        scanned += 1
        source = path.read_text(encoding="utf-8")
        # Names only: comments and strings are prose, and the prose in this
        # package is largely *about* not checking out.
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            if token.type != tokenize.NAME:
                continue
            assert not banned.match(token.string), (
                f"{path}:{token.start[0]}: {token.string}"
            )
    assert scanned >= 7, f"only scanned {scanned} modules"


# ---------------------------------------------------------------------------
# jarvis_bots.api: the four endpoints, and the page that has to find them
# ---------------------------------------------------------------------------


def test_the_api_module_the_cli_has_always_named_exists_and_serves_four_routes():
    """``cli.py`` binds to ``jarvis_bots.api`` by shape and falls back to
    the supervisor when it is missing, so the module's absence was
    invisible -- and so was the hole under it: nothing in the package
    could produce the detail payload the scaffold's own page reads."""
    from jarvis_bots import api

    clock = Clock()
    bot = ScriptedBot(clock, "poke", [[(Severity.ACTION, "k", None)]])
    sup = Supervisor(BotRegistry([bot]), clock)
    sup.run_round(clock.at)

    assert sorted(api.launcher_state(sup)) == ["bots", "generated_at"]
    assert sorted(api.badge_status(sup)) == ["attention", "state"]
    assert sorted(api.bot_detail(sup, "poke")) == ["bot", "generated_at"]
    assert api.set_paused(sup, {"bot_id": "poke", "paused": True}) == sup.badge_status()
    assert sup.is_paused("poke")

    with pytest.raises(api.ApiError) as bad_id:
        api.bot_detail(sup, "nope")
    assert bad_id.value.status == 404
    with pytest.raises(api.ApiError) as bad_body:
        api.set_paused(sup, {"bot_id": "poke"})
    assert bad_body.value.status == 400
    with pytest.raises(api.ApiError) as unknown:
        api.set_paused(sup, {"bot_id": "nope", "paused": True})
    assert unknown.value.status == 404


def test_the_cli_prints_the_detail_payload_so_a_page_needs_no_server():
    from jarvis_bots import api, cli

    clock = Clock()
    bot = ScriptedBot(clock, "poke", [[(Severity.ACTION, "k", None)]])
    sup = Supervisor(BotRegistry([bot]), clock)
    sup.run_round(clock.at)
    assert cli.detail_payload(sup, "poke", clock.at) == api.bot_detail(sup, "poke", clock.at)


def test_the_readme_says_how_to_point_the_page_at_the_api():
    """The single most expensive omission in this package: `bots.html`
    reads `window.JARVIS_BOTS_API` and the README that documents the file
    never mentioned it, so following the README to the letter with a
    correct backend rendered three invented bots, silently."""
    readme = (WEB / "README.md").read_text(encoding="utf-8")
    page = (WEB / "bots.html").read_text(encoding="utf-8")

    for switch in re.findall(r"window\.(JARVIS_BOTS?_API)", page):
        assert switch in readme, f"{switch} is how the page is wired and is undocumented"
    for name in re.findall(r'meta\[name="([a-z-]+)"\]', page):
        assert name in readme, f"the {name} meta tag is undocumented"

    # And with nobody saying anything, the page has a default rather than
    # a silent fallback to invented data.
    assert re.search(r'DEFAULT_API\s*=\s*"/api/bots/"', page)
    assert "/api/bots/<id>" in readme


def test_the_generated_page_and_the_launcher_agree_on_how_they_are_wired():
    template = (ROOT / "jarvis_bots" / "templates" / "page.html.tmpl").read_text("utf-8")
    readme = (WEB / "README.md").read_text(encoding="utf-8")
    assert "JARVIS_BOT_API" in readme
    assert 'DEFAULT_API = "/api/bots/@@BOT_ID@@"' in template
    assert 'meta[name="jarvis-bot-api"]' in template


def test_the_nav_badge_is_visible_for_every_state_the_supervisor_can_report():
    """A quarantined bot creates no attention item and pausing one clears
    its items, so both arrive at the button as attention: 0. The badge was
    hidden on that, which made a paused or failing fleet pixel-identical
    to a healthy one."""
    script = (WEB / "bots-button.js").read_text(encoding="utf-8")
    render = re.search(r"#render\(\) \{(.*?)\n  \}", script, re.S)
    assert render is not None
    assert "state !== 'ok'" in render.group(1), "badge hidden for warn/error"
    assert ".badge.dot" in script

    # and the supervisor really does report those states with no attention
    clock = Clock()
    bot = ScriptedBot(clock, "poke", [[]])
    sup = Supervisor(BotRegistry([bot]), clock)
    sup.pause("poke")
    assert sup.badge_status() == {"attention": 0, "state": "warn"}


def test_the_button_can_only_ever_have_one_poll_loop():
    """An aborted poll used to return normally and re-arm itself, so every
    attribute change added a loop that #stop() could no longer reach."""
    script = (WEB / "bots-button.js").read_text(encoding="utf-8")
    assert "#generation" in script
    stop = re.search(r"#stop\(\) \{(.*?)\n  \}", script, re.S)
    assert stop is not None and "#generation += 1" in stop.group(1)
    schedule = re.search(r"\n  #schedule\(\{.*?\n  \}", script, re.S)
    assert schedule is not None
    assert schedule.group(0).count("mine !== this.#generation") >= 2
    # even the first poll goes through a cancellable timer, so the three
    # attributeChangedCallbacks fired during upgrade collapse into one
    assert "immediate ? 0 :" in schedule.group(0)
